"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""

fib_list = []

x, y = 1, 1
while x<4000000:
    y, x = x, y
    x+=y
    fib_list.append(y)

even_fib = []
for fib in fib_list:
    if fib%2 == 0:
        even_fib.append(fib)

print(sum(even_fib))
